apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      name: openhab-http
    - protocol: TCP
      port: 8083
      name: openhab-https
  type: LoadBalancer
