kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data-pv
  namespace: monitoring
  annotations:
#    volume.beta.kubernetes.io/storage-class: "nfs-master-ssd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
