apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-core
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        component: core
    spec:
      containers:
      - image: fg2it/grafana-armhf:v5.0.0-beta4
        name: grafana-core
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
        env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
          - name: GF_PATHS_PLUGINS
            value: "/var/lib/grafana/plugins"
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
          readOnly: false
        ports:
        - name: webui
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /login
            port: webui
          initialDelaySeconds: 30
          timeoutSeconds: 3
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data-pv
