kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data-pv
  namespace: monitoring
  annotations:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
