apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openhab
  namespace: openhab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
      - name: openhab
        image: openhab/openhab:2.5.0.M1-armhf-debian
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: USER_ID
            value: "1000"
          - name: GROUP_ID
            value: "1000"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8101
          name: console
          protocol: TCP
        volumeMounts:
        - name: etc-localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: openhab-conf
          mountPath: /openhab/conf
          readOnly: false
        - name: openhab-userdata
          mountPath: /openhab/userdata
          readOnly: false
        - name: openhab-addons
          mountPath: /openhab/addons
          readOnly: false
        - name: openhab-java
          mountPath: /openhab/.java
          readOnly: false
        - name: openhab-karaf
          mountPath: /openhab/.karaf
          readOnly: false
        env:
          - name: USER_ID
            value: "1000"
          - name: GROUP_ID
            value: "1000"
      volumes:
      - name: openhab-conf
        persistentVolumeClaim:
          claimName: openhab-conf-pv
      - name: openhab-userdata
        persistentVolumeClaim:
          claimName: openhab-userdata-pv
      - name: openhab-addons
        persistentVolumeClaim:
          claimName: openhab-addons-pv
      - name: openhab-java
        persistentVolumeClaim:
          claimName: openhab-java-pv
      - name: openhab-karaf
        persistentVolumeClaim:
          claimName: openhab-karaf-pv
      - name: etc-localtime
        hostPath:
          path: /usr/share/zoneinfo/Europe/Madrid
      terminationGracePeriodSeconds: 300
