kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquito-db-pv
  namespace: openhab
  annotations:
#    volume.beta.kubernetes.io/storage-class: "nfs-master-ssd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
